### ISSUE TITLE
How do I add branch 17 to my build? 

### ISSUE THREAD

**Issue by iot-resister** [LineageOS/android_device_lenovo_YTX703-common#1]
I'm trying to simply upgrade from twrp/16.0 to lineage recovery/17.    This is what I've done so far

1. `$ repo init -u https://github.com/LineageOS/android.git -b lineage-17.0 && repo sync`

2.  Edit (diff) `./lineage/wiki/_data/devices/YTX703F.yml`

	```git
	@@ -8,7 +8,7 @@ codename: YTX703F
 	cpu: Cortex-A53 & Cortex-A72
 	cpu_cores: '8'
 	cpu_freq: 4 x 1.8 GHz & 4 x 1.4 GHz
	-current_branch: 16.0
	+current_branch: 17.0
	 custom_recovery_codename: yt_x703f

	@@ -37,6 +37,6 @@ type: tablet
 	uses_twrp: true
 	vendor: Lenovo
 	vendor_short: lenovo
	-versions: [15.1, 16.0]
	+versions: [15.1, 17.0]
 	width: 247 mm (9.7 in)
	```  

   3.  `$ repo sync`
   4.  Copy the common repo into the device tree and checkout branch 17.0
   4.  `$ source build/envsetup.sh && breakfast YTX703`
   5.  `/extract-files.sh` and it connects and begins extracting from the device 

**Error**: 
```
- recovery/root/vendor/lib64/libtime_genoff.so
/device/lenovo/YTX703-common/YTX703F/../extract-files.sh: line 213: YTX703F/extract-files.sh: No such file or directory
```

It dies at `- recovery/root/vendor/lib64/libtime_genoff.so`  

Not sure how to move forward.

**Comment by Quallenauge** [comment]
There's no pushed changes in official lineage "lineage-17.1" branch, so you would end up in a non build able setup (which you you have experienced).

At best you learn about using local manifests. Then you create one YTX703.xml file and place ist in .repo/local_manifests/YTX703L.xml of your checked out branch. An example is listed here:
```
<?xml version="1.0" encoding="UTF-8"?>
<manifest>
  <remote  name="omnirom" fetch="https://github.com/omnirom" review="gerrit.omnirom.org" revision="android-8.1" />
  <remote  name="twrp" fetch="https://gerrit.twrp.me" review="gerrit.twrp.me" revision="android-9.0" />
  <project path="device/lenovo/YTX703F"         name="LineageOS/android_device_lenovo_YTX703F"        revision="lineage-17.1" />
  <project path="device/lenovo/YTX703L"         name="LineageOS/android_device_lenovo_YTX703L"        revision="lineage-17.1" />
  <project path="device/lenovo/YTX703-common"   name="LineageOS/android_device_lenovo_YTX703-common"  revision="lineage-17.1" />
  <project path="kernel/lenovo/msm8976"         name="LineageOS/android_kernel_lenovo_msm8976"        revision="lineage-17.1" />
  <project path="vendor/lenovo"                 name="Quallenauge/proprietary_vendor_lenovo"            revision="lineage-17.1"/>
  <project name="LineageOS/android_hardware_sony_timekeep" path="hardware/sony/timekeep" remote="github" revision="lineage-17.1" />
</manifest>
```

Then run `repo sync` and try again to build with brunch.

**Comment by iot-resister** [comment]
@Quallenauge  Thank so much!

**Comment by iot-resister** [comment]
@Quallenauge  Thanks so much. I registered for android filehost. But its saying access denied ?

**Comment by Quallenauge** [comment]
Sorry, wrong links.

Ytx703f: https://androidfilehost.com/?a=show&w=files&flid=305523

Ytx703l: https://androidfilehost.com/?a=show&w=files&flid=305522

**Comment by iot-resister** [comment]
You wrote
>Then you create one YTX703.xml file and place ist in .repo/local_manifests/YTX703L.xml 


My device is the YTX703F.

Is the correct xml path:

`.repo/local_manifests/YTX703F.xml`

or 
`.repo/local_manifests/YTX703.xml`

?

**Comment by iot-resister** [comment]
nvm. Its not finished building yet but I def this it was `.repo/local_manifests/YTX703F.xml`.  @Quallenauge  you are awesome. Than ks for helping me! Great project!
